#!/bin/sh
# bootstrap gnucobol/build_aux
# Bootstrap gnucobol package from checked-out sources
# Note:  call as ./bootstrap if you don't have readlink -f
#
# Copyright (C) 2017-2018 Free Software Foundation, Inc.
# Written by Simon Sobisch
#
# This file is part of GnuCOBOL.
#
# The GnuCOBOL compiler is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# GnuCOBOL is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GnuCOBOL.  If not, see <http://www.gnu.org/licenses/>.

echo start to bootstrap GnuCOBOL
ret=0
# get path to GnuCOBOL main directory
if test "$0" = "./bootstrap"; then
	MAINPATH=..
else
	MAINPATH=$(dirname $(readlink -f "$0"))/..
fi

echo
if test ! -f $MAINPATH/tarstamp.h; then
	echo creating tarstamp.h...
	echo "#define COB_TAR_DATE \"`date -u +'%b %d %Y %T'` UTC\"" > $MAINPATH/tarstamp.h
	echo "#define COB_NUM_TAR_DATE `date -u +'%Y%m%d'`" >> $MAINPATH/tarstamp.h
	echo "#define COB_NUM_TAR_TIME `date -u +'%H%M%S'`" >> $MAINPATH/tarstamp.h
else
	echo tarstamp.h exists already
fi

echo; echo ensure that we have executable scripts...
chmod +x $MAINPATH/build_aux/compile
chmod +x $MAINPATH/build_aux/config.guess
chmod +x $MAINPATH/build_aux/config.rpath
chmod +x $MAINPATH/build_aux/config.sub
chmod +x $MAINPATH/build_aux/depcomp
chmod +x $MAINPATH/build_aux/install-sh
chmod +x $MAINPATH/build_aux/ltmain.sh
chmod +x $MAINPATH/build_aux/mdate-sh
chmod +x $MAINPATH/build_aux/missing
chmod +x $MAINPATH/build_aux/mkinstalldirs
chmod +x $MAINPATH/build_aux/ylwrap
chmod +x $MAINPATH/doc/cobcinfo.sh
chmod +x $MAINPATH/po/update_linguas.sh
chmod +x $MAINPATH/tests/listings-sed.sh
if test -f $MAINPATH/create_win_dist.sh; then
	chmod +x $MAINPATH/create_win_dist.sh
fi

echo; echo running autoreconf...
#autoreconf -I m4 --install --force		# changing build_aux scripts
autoreconf -I m4 --verbose --force $MAINPATH; ret=$?
if test $ret -ne 0; then
	echo; echo ERROR - aborting bootstrap && exit $ret
fi

echo; echo bootstrap is finished
